name: Build

on:
  workflow_call:
  push:
    branches:
      - main

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: dart-lang/setup-dart@v1

      - name: Build
        run: make linux

      - uses: actions/upload-artifact@v7
        with:
          name: photo_labeler-linux
          path: build/photo_labeler

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7

      - uses: dart-lang/setup-dart@v1

      - name: Install 7-Zip and make
        run: choco install 7zip make -y

      - name: Build
        run: make windows

      - uses: actions/upload-artifact@v7
        with:
          name: photo_labeler-windows
          path: build/photo_labeler.exe
