name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v7
        with:
          name: photo_labeler-linux
          path: photo_labeler-linux

      - uses: actions/download-artifact@v7
        with:
          name: photo_labeler-windows
          path: photo_labeler-windows

      - name: Prepare release binaries
        run: |
          mv photo_labeler-linux/photo_labeler "photo_labeler-linux-x64-${{ github.ref_name }}"
          mv photo_labeler-windows/photo_labeler.exe "photo_labeler-windows-x64-${{ github.ref_name }}.exe"

      - name: Create release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            photo_labeler-linux-x64-${{ github.ref_name }}
            photo_labeler-windows-x64-${{ github.ref_name }}.exe
